version: '3'

services:
  student:
    image: mahuntington/student:postgres
    stdin_open: true
    tty: true
    container_name: student
    command: ["pg_ctlcluster", "15", "main", "start", "--foreground"]
