version: '3'

services:
  student:
    image: mahuntington/student:python
    stdin_open: true
    tty: true
    container_name: student
    working_dir: /home/student
    command: ["pg_ctlcluster", "15", "main", "start", "--foreground"]
    volumes:
      - .:/home/student/dev
